config/routes.rb
Rails.application.routes.draw do

  devise_for :users
#   devise_scope :user do get "/users/sign_in" => "devise/sessions#new"
# end
  # root 'devise/sessions#new'
  root 'units#index'

  get 'units/group/:id' => 'units#group', as: :units_group
  get 'units/search' => 'units#search', as: :units_search
  get 'units/complite/:id' => 'units#complite', as: :units_complite
  get 'units/group_complite/:id' => 'units#group_complite', as: :units_group_complite
  get 'authors/department/:id' => 'authors#department', as: :authors_department

  resources :authors, :users, :units, except: [:destroy]
  resources :temp_tasks, :departments, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :temp_tasks
    has_many :units
    
    validates :name, :phone, :department_id, presence: true
    
    def self.author_select
    Author.all.map {|author| [author.name, author.id]}
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
     def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    @author.save
    # redirect_to new_temp_task_path
  end

  def show
    @author = Author.find(params[:id])
    # @units = Unit.where(author_id: params[:id])
    # @department = Department.all
  end

  # def department
  #   @authors = Author.where(id: params[:id], department_id: params[:department_id])
  # end

  def index
    @authors = Author.all
  end

  def edit
    @author = Author.find params[:id]
  end

  def update
    @author = Author.find params[:id]
    if @author.update(author_params)
      redirect_to author_path(@author)
    else
      render 'edit'
    end
  end

  private
  def author_params
    params.require(:author).permit(:name, :phone, :department_id, :photo)
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/views/authors/_author.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <%= simple_form_for @author do |f| %>
        <%= f.input :name %>
        <%= f.input :phone %>
        <%= f.input_field :department %>
        <%= f.input :photo %>
        <%= f.submit 'Добавить' %>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/department.html.erb
<% @authors.each do |author| %>
<%= author.department %>
<% end %>

<% @authors.each do |author| %> 
<%= author.name %>
<% end %>

app/views/authors/edit.html.erb
<%= render 'author' %>

app/views/authors/index.html.erb
<div class="container">
<table class="table table-condensed">
	<thead>
				<tr>
					<th>Автор</th>
					<th>Телефон</th>
					<th>Подразделение</th>
					<th>Фото</th>
				</tr>
	</thead>
	<tbody>
	<% @authors.each do |author| %>
	<tr>
			<td><%= link_to author.name, edit_author_path(author) %></td>
			<td><%= author.phone %></td>
			<td><%= author.department %></td>
		<td><a class="btn btn-default" href="/tasks_temps/new" role="button">Редактировать</a></td>
	</tr>
	<% end %>
 </table>
</div>

app/views/authors/new.html.erb
<%= render 'author' %>

app/views/authors/show.html.erb
<div class="container">
    <div class="row">
    <div class="col-md-6">
    <img src="<%= @author.photo %>" class="rounded float-right" alt="Аватарка">
    </div>
    <div class="col-md-6">
    <p><%= link_to @author.name, edit_author_path %></p>
    <p><%= @author.phone %></p>
    <p><%= link_to @author.department_id, authors_department_path(@author) %></p>
    </div>
    </div>
	<table class="table table-condensed">
		<thead>
			<tr>
				<th>Компания</th>
				<th>Дата завершения</th>
				<th>Исполнитель</th>
			</tr>
		</thead>
<tbody>
<% @author.units.each do |unit| %>
	
	<% @date_result = (unit.date_end - Date.today).to_i %>
  		
	
	<tr class=<%= color %>>
		<td><%= unit.unit %></td>
		<td><%= l unit.date_end, format: :long %></td>
		<td><%= unit.user.name %></td>
	</tr>
<% end %>
	</tbody>
</table>
</div>