config/routes.rb
Rails.application.routes.draw do

  devise_for :users
#   devise_scope :user do get "/users/sign_in" => "devise/sessions#new"
# end
  # root 'devise/sessions#new'
  root 'units#index'

  get 'units/group/:id' => 'units#group', as: :units_group
  get 'units/search' => 'units#search', as: :units_search
  get 'units/complite/:id' => 'units#complite', as: :units_complite
  get 'units/group_complite/:id' => 'units#group_complite', as: :units_group_complite
  get 'authors/department/:id' => 'authors#department', as: :authors_department

  resources :authors, :users, :units, except: [:destroy]
  resources :temp_tasks, :departments, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :authentication_keys => [:name]
  devise :registerable,
         :recoverable, :rememberable, :validatable
    has_many :units
    has_many :temp_tasks

  validates :name, presence: true, format:{ :with => /[а-яА-Я]+/ }


  def email_required?
    false
  end

  def email_changed?
    false
  end



  def self.user_select
    User.all.map {|user| [user.name, user.id]}
  end

  def self.user_out
    User.where(in_out: true).user_select
  end

  def self.admin
    User.where(role: 0).where(branch_id: 0).user_out
  end

  # scope :admin, -> { where(branch_id: 0) }

  # def self.user_sel
  #   user_select.where(in_out: true)
  # end

  # def user
  #   @user = User.all.map{ |user| [user.name, user.id] }
  # end

  # scope :pub, -> { where(complete: false) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @units = Unit.where(user_id: params[:id], complete: false).order(:date_end)
  end

  def index
  end

  def edit
    @users = User.all
  end

  def admin
    @users = User.all
  end


end

app/helpers/user_helper.rb
module UserHelper
    def find_count(user)
   Unit.where(user_id:  "#{user.id}", complete: false).size
 end
end

app/views/users/_alert_form_group.html.erb
<div>
	<% @units do |item| %>
		<%= simple_form_for(item) do |f| %>
			<%= f.input :date_finish %>
		  <%= f.input :sum_ur %>
			<%= f.input :sum_fiz %>
			<%= f.input :comment %>
			<%= f.input :complete, as: :boolean %>
			<%= f.button :submit %>
		<% end %>
	<% end %>
</div>

app/views/users/admin.html.erb
<% @users.each do |user| %>
<%=  user.name %>
<%= user.role %>
<% end %>

app/views/users/edit.html.erb
<!--форма для назначения прав админа-->

<div class="container">
	<table class="table table-condensed">
		<thead>
			<tr>
				<th>Login</th>
				<th>Admin?</th>
				<th>email</th>
				
			</tr>
		</thead>
<tbody>
<% @users.each do |user| %>
<tr>
		<td><%= user.name %></td>
		<td><%= user.role %></td>
		<td><%= user.email %></td>
</tr>
<% end %>
	</tbody>
</table>
</div>

app/views/users/index.html.erb
<div class="container">
<% @users.each do |user| %>
<p>
    <div class="btn-group" role="group">
<%= button_to "#{user.name} #{find_count(user)}", user_path(user), method: :get, class: "btn btn-success" %>
    </div>
</p>
<% end %>



</div>

app/views/users/show.html.erb
<div class="container">
	<table class="table table-condensed">
		<thead>
			<tr>
				<th>Компания</th>
				<th>Дата завершения</th>
				<th>Инициатор</th>
				
			</tr>
		</thead>
<tbody>
<% @units.each do |unit| %>
	<% @date_result = (unit.date_end - Date.today).to_i %>
	
	<tr class=<%= color %>>
		<td><%= unit.unit %></td>
		<td><%= l unit.date_end, format: :long %></td>
		<td><%= link_to unit.author.name, author_path(unit.author_id) %></td>
		<td><%= link_to units_group_complite_path(unit.id_temp_task), :class=> "glyphicon glyphicon-floppy-saved" do %></td>
		<% end %>
		<td><%= link_to '',data: { id_temp_task: unit.id_temp_task } , class: "glyphicon glyphicon-floppy-saved floppy" do %><% end %></td>  
		
	</tr>
<% end %>
	</tbody>
</table>



</div>