config/routes.rb
Rails.application.routes.draw do

  devise_for :users
#   devise_scope :user do get "/users/sign_in" => "devise/sessions#new"
# end
  # root 'devise/sessions#new'
  root 'units#index'

  get 'units/group/:id' => 'units#group', as: :units_group
  get 'units/search' => 'units#search', as: :units_search
  get 'units/complite/:id' => 'units#complite', as: :units_complite
  get 'units/group_complite/:id' => 'units#group_complite', as: :units_group_complite
  get 'authors/department/:id' => 'authors#department', as: :authors_department

  resources :authors, :users, :units, except: [:destroy]
  resources :temp_tasks, :departments, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :date_start, :date_end, presence: true
  belongs_to :user
  belongs_to :author
  
  scope :blok, -> { where(:complete => false) }
  
  # def self.blok
  #   .where(complete: false)
  # end
  
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def new
    @temps = TempTask.last
    a = JSON.parse(@temps.to_json).to_a.shift(9)
    a[1][1].split(/; /).map{|item| Unit.create(
    {'unit': item, 'id_temp_task': a[0][1], 'date_start': a[2][1], 'date_end': a[3][1],
    'author_id': a[4][1], 'user_id': a[5][1], 'branch_id': a[8][1] }
    )}
    @temps.destroy
    redirect_to root_path
  end

  def show
    edit
  end

  def complite
    edit
    if @unit.update(unit_params)
      redirect_to units_path
    else
      render 'complite'
    end
  end

  def search
    @searchs = if params[:term]
      Unit.where('unit LIKE ?', "%#{params[:term]}%")
    else
      Unit.all
    end
  end

    CBR = 'https://www.cbr.ru/analytics/?PrtId=insideinfo'
    CRASH = 'Сообщение об отзыве лицензии на осуществление банковских операций'

  def index
    @units = Unit.where(complete: false).order(:date_end)
    @users = User.all
    @author = Author.new
    @department = Department.new
    cbr
  end

  def cbr
    decline = Nokogiri::HTML(open(CBR)).css('ul.without_dash:nth-child(7) > li')
    date = decline.map{|x| x.css('span.smallest').inner_text}.map{|x| Date.parse(x)}
    url = decline.map{|x| x.css('a')[0]}.map{|x| "https://www.cbr.ru#{x['href']}"}
    head = decline.map{|x| x.css('a')[0]}.map{|x| x.inner_text}
    arr = date.zip(url, head).keep_if{ |x| x[0] == Date.today}.keep_if{ |x| x[2] == 'Сообщение об отзыве лицензии на осуществление банковских операций'}
    @u = arr.map{|x| Nokogiri::HTML(open("#{x[1]}")).css('#content')}
  end

  def edit
    @unit = Unit.find params[:id]
  end

  def group
    @units = Unit.where(id_temp_task: params[:id])
  end

  def complite
    @unit = Unit.find params[:id]
  end

  def group_complite
    @units = Unit.where(id_temp_task: params[:id]).where(complete: false).where(user_id: current_user)
    respond_to do |format|
      # format.html # index.html.erb
      format.js { render js: @units}
    end
  end

  def update
    edit
    if @unit.update(unit_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

   private

  def unit_params
    params.require(:unit).permit(:unit, :date_start, :date_end, :date_finish, :author_id, :user_id, :complete, :comment, :sum_ur, :sum_fiz, :id_temp_task, :branch_id)
  end

  def search_params
    params.require(:search).permit(:unit, :date_end, :author_id, :user_id, :term, :comment, :sum_ur, :sum_fiz, :id_temp_task)
  end
end

app/helpers/unit_helper.rb
module UnitHelper
    def color
      if @date_result == 0
         "list-group-item-warning"
      elsif @date_result > 0
         "list-group-item-success"
      else
         "list-group-item-danger"
      end
    end
end

app/views/units/_add_departament.html.erb
<div class="add_departament" style="display: none;">
	<%= form_for :department, :url => {:controller => 'departments', action: "create", role: 'form'} do |f| %>
		<div class="form-inline margin_bottom">
			<%= f.text_field :full_department, {:class => 'form-control department_style', :placeholder => "", :type => 'text'} %>
			<%= f.submit "Сохранить", class: "btn btn-primary", id: "save_dep" %>
		</div>
	<% end %>
</div>

app/views/units/_add_form.html.erb
<div class="add_task" style="display: none;">

  <%= form_for :temp_task, :url => {:controller => 'temp_tasks', action: "create", role: 'form'} do |f| %>
	<div class="form-inline">
		<%= f.text_field :date_start, {:class => 'datepicker date-width', :placeholder => 'Дата начала'} %>
		<%= f.text_field :date_end, {:class => 'datepicker date-width', :placeholder => 'Дата окончания'} %>
	</div>

	<div>
		<%= f.text_area :companys, rows: 2, class: 'form-control add_company', placeholder: 'Несколько компаний  через ";"' %>
	</div>

	<div class="form-inline margin_bottom">
		<label>Инициаторы</label>
		<%= f.select :author_id, Author.author_select, {:placeholder => ""}, {:class => 'form-control add_company_author'} %>
		<div class="author btn btn-sm btn-info">добавить инициатора</div>
	</div>

	<div class="form-inline">
		<div class="form-inline">
	        <%= f.hidden_field :branch_id, :value => current_user.branch_id %>
	    </div>
	    
		<label>Исполнители</label>
		<%= f.select :user_id, User.where(branch_id: current_user.branch_id).user_out, {:placeholder => ""}, {:class => 'form-control add_company_user'} %>
		<%= f.submit "Сохранить задачу", class: "btn btn-primary" %>
	</div>

  <% end %>
</div>

app/views/units/_author.html.erb
<div class="author-tab" style="display: none;">

  <%= form_for :author, :url => {:controller => 'authors', action: "create", role: 'form'} do |f| %>
    <%= f.text_field :name, {:class => 'form-control',:id => 'authors_style_name', :placeholder => 'ФИО', :type => 'text'} %>
    <%= f.text_field :photo, {:class => 'form-control authors_style_photo', :placeholder => 'Фото - url', :type => 'url'} %>

    <div class="form-inline margin_bottom">
      <div class="form-group">
      <label>Департамент:</label>
        <%= f.select :department_id, Department.all.map{ |department| [department.short_department, department.id] }, {:placeholder => ""}, {:class => 'form-control authors_style', :id => 'form_for_reload'} %>
      </div>
      <button type="button" class="btn btn-info color_btn">Добавить департамент</button>
    </div>
    <div class="form-inline margin_bottom">
      <%= f.text_field :phone, {:class => 'form-control authors_style_phone', :placeholder => 'Телефон'} %>
      <%= f.submit "Сохранить инициатора", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/units/_cbr.html.erb
<div class="row">
	<table class="table table-condensed">
		<tbody>
			<% @u.each do |x| %>
				<tr class="danger">
				<td><h3><%= x.css('h1').text %></h3>
				<em><%= x.css('p').inner_text %></em></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/units/_form_edit.html.erb
<tr id="edit_unit_<%= thing.id %>" style="display: none;">
	<%= simple_form_for(thing) do |f| %>
		<td>
			<%= button_tag type: 'submit', class: "btn btn-default" do %>
      	<i class="glyphicon glyphicon-ok ok" aria-hidden="true"></i>
  		<% end %>
			<%= link_to '',data: { unit_id: thing.id } , class: 'btn btn-default remove' do %>
				<i class="glyphicon glyphicon-remove" aria-hidden="true"></i>
			<% end %>
		</td>	  
		<td><%= f.input :unit, label: false %></td>
		<td>
			<%= f.text_field :date_start, {:class => 'datepicker'} %>
			<%= f.text_field :date_end, {:class => 'datepicker'} %>
		</td>
		<td>
			<%= f.input :user_id, label: false do %>
				<%= f.select :user_id, User.where(branch_id: current_user.branch_id).user_out, {:placeholder => ""}, {:class => 'form-control'} %>
			<% end %>		
		</td>
		<td>
			<%= f.input :author_id, label: false do %>
			  <%= f.select :author_id, Author.author_select, {:placeholder => ""}, {:class => 'form-control'} %>
			<% end %>
		</td>
	<% end %>
</tr>
			

app/views/units/_search.html.erb
<div class='container'>
<table class="table table-condensed">
		<thead>
			<tr>
				<th>Компания</th>
				<th>Дата завершения</th>
				<th>Комментарий</th>
				<th>Количество Юриков</th>
				<th>Количество Физиков</th>
				<th>Исполнитель</th>
				<th>Инициатор</th>
				<th>Завершено</th>
			</tr>
		</thead>
<tbody>
	<!--if current_user.branch_id == unit.branch_id-->
    <% @searchs.each do |search| %>
    	<td><%= link_to search.unit, units_group_path(search.id_temp_task) %></td>
		<td><%= l search.date_end, format: :long %></td>
		<td><%= search.comment %></td>
		<td><%= search.sum_ur %></td>
		<td><%= search.sum_fiz %></td>
		<td><%= search.user.name %></td>
		<td><%= search.author.name %></td>
		<td><%= search.complete%></td>
		
		
	</tr>
<% end %>
<!--end-->
	</tbody>
</table>
</div>
 </div>

app/views/units/_table.html.erb
<table class="table">
	<thead>
		<tr>
			<th></th>
			<th>Компания</th>
			<th>Дата завершения</th>
			<th>Исполнитель</th>
			<th>Инициатор</th>	
		</tr>
	</thead>
	<tbody class="tab" id="table">
		<% @units.each do |unit| %>
			<% case %>
				<% when current_user.branch_id == 0 %>
					<% @date_result = (unit.date_end - Date.today).to_i %>
					<tr class=<%= color %>>
						<td><%= link_to edit_unit_path(unit),  class: "glyphicon glyphicon-pencil pencil" do %></td>
						<% end %>
						<td><%= link_to unit.unit, units_group_path(unit.id_temp_task) %></td>
						<td><%= l unit.date_end, format: :long, prompt: :translate %></td>
						<td><%= link_to unit.user.name, user_path(unit.user_id) if !unit.user_id.nil? %></td>
						<td><%= link_to unit.author.name, author_path(unit.author_id) %></td>
					</tr>
						<%= render 'form_edit', :thing => unit %>
				

				<% when current_user.branch_id == unit.branch_id %>
					<% @date_result = (unit.date_end - Date.today).to_i %>
					<tr id="unit_<%= unit.id %>" class=<%= color %>>

						<td><%= link_to '',data: { unit_id: unit.id } , class: 'glyphicon glyphicon-pencil pencil' do %><% end %></td>
						
						<td><%= link_to unit.unit, units_group_path(unit.id_temp_task) %></td>
						<td><%= link_to unit.date_end, format: :long, prompt: :translate %></td>
						<td><%= link_to unit.user.name, user_path(unit.user_id) if !unit.user_id.nil? %></td>
						<td><%= link_to unit.author.name, author_path(unit.author_id) %></td>
					</tr>

						<%= render 'form_edit', :thing => unit %>

			<% end %>
		<% end %>
	</tbody>
</table>

app/views/units/complite.html.erb
<div class="container">
	<div class="row">
	<div class="col-md-6"> 
			<%= simple_form_for(@unit) do |f| %>
			<%= f.input :date_finish %>
            <%= f.input :sum_ur %>
			<%= f.input :sum_fiz %>
			<%= f.input :comment %>
			<%= f.input :complete, as: :boolean %>
			<%= f.button :submit %>
			<% end %>
		</div>
	</div>
</div>

app/views/units/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col"> 
			<%= simple_form_for(@unit) do |f| %>
				<div class="form-inline">
					<%= f.input :unit, label: false %>
					<%= f.text_field :date_start, {:class => 'datepicker'} %>
					<%= f.text_field :date_end, {:class => 'datepicker'} %>
					<%= f.input :author_id, label: false do %>
		        		<%= f.select :author_id, Author.author_select, {:placeholder => ""}, {:class => 'form-control'} %>
		        	<% end %>
		        	<%= f.input :user_id, label: false do %>
						<%= f.select :user_id, User.where(branch_id: current_user.branch_id).user_out, {:placeholder => ""}, {:class => 'form-control'} %>
					<% end %>
					<%= f.button :submit, label: false %>
				</div>

			<% end %>
		</div>
	</div>
</div>

app/views/units/group.html.erb
<div class="container">
	<table class="table table-condensed">
		<thead>
			<tr>
				<th>Компания</th>
				<th>Дата завершения</th>
				<th>Исполнитель</th>
				<th>Инициатор</th>
			</tr>
		</thead>
		<tbody>
			<% @units.each do |unit| %>
				<% if unit.date_end.month == Time.now.month %>
			  	<% @date_result = unit.date_end.day - Time.now.day %>
			 	<% else %>
			  	<% @date_result = 3 %>
				<% end %>
			<tr class=<%= color %>>
				<td><%= unit.unit %></td>
				<td><%= l unit.date_end, format: :long %></td>
				<td><%= link_to unit.user.name, user_path(unit.user_id) if !unit.user_id.nil? %></td>
				<td><%= link_to unit.author.name, author_path(unit.author_id) %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/units/group_complite.html.erb
<table class="table table-condensed">
	<thead>
		<tr>
			<th>Компания</th>
			<th>Дата завершения</th>
			<th>Исполнитель</th>
			<th>Инициатор</th>
		</tr>
	</thead>
	<tbody>
		<% @units.each do |unit| %>
			<% if unit.date_end.month == Time.now.month %>
		  	<% @date_result = unit.date_end.day - Time.now.day %>
		 	<% else %>
		  	<% @date_result = 3 %>
			<% end %>
		<tr class=<%= color %>>
			<td><%= unit.unit , data: { unit: unit.unit } %></td>
			<td><%= l unit.date_end, format: :long %></td>
			<td><%= link_to unit.user.name, user_path(unit.user_id) if !unit.user_id.nil? %></td>
			<td><%= link_to unit.author.name, author_path(unit.author_id) %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/units/index.html.erb
<div class="container">
	<%= render 'cbr' %>

	<div class="row" id="cont">
	  <table id="user-list">
        <tr>
	      <div class="col-xs-8 left-names">
			<% @users.each do |user| %>
	    	  <td class="names btn-group">
				<% if user.in_out? %>
				<% case user.in_out? %>
					<% when current_user.branch_id == 0 %>
				  		<%= button_to [user.name, find_count(user)], user_path(user), method: :get, class: "btn btn-success btn-lg btn-zenit" %>
					<% when current_user.branch_id == user.branch_id %>
						<%= button_to [user.name, find_count(user)], user_path(user), method: :get, class: "btn btn-success btn-lg btn-zenit" %>
					<% end %>
				<% end %>
			  </td>
			<% end %>
		  </div>
	   	  <div class="col-xs-4">
	 		  <td>
	 		    <div class="task btn btn-primary btn-lg">Добавить задачу</div>
			  </td>
			</div>
		</tr>
	  </table>
	</div>

	<br>
	<div class="row" id="forms_css">
	  <div class="col-xs-7">
	  	<%= render 'add_form' %>
	  </div>
	  <div class="col-xs-5">
			<%= render 'author' %>
		    <%= render 'add_departament' %>
		</div>
	</div>
	
	<br>
	<div class="row">
		<div class="col-xs-12">
			<%= render 'table' %>
		</div>			
	</div>
<div>
    <table>
        <% @users.each do |user| %>
        <tr>
            <th><%=  user.name %></th>
            <th><%=  user.branch_id %></th>
            <th><%= current_user.branch_id == user.branch_id %></th>
            <th><%= check_box_tag(:role) %></th>
            <th><%= label_tag(:role, "supeuser") %></th>
            <th><%= check_box_tag(:role) %></th>
            <th><%= label_tag(:role, "admin") %></th>
            <th><%= check_box_tag(:role) %></th>
            <th><%= label_tag(:role, "user") %></th>
            <th><%= user.in_out? %></th>
            <th><%= check_box_tag(:in_out) %></th>
            <th><%= label_tag(:in_out, "уволен") %></th>
        </tr>	
        <% end %>
    </table>
</div>
</div>

app/views/units/search.html.erb
<%= render 'search' %>

app/views/units/show.html.erb
<div class="container">
<%= @unit.unit %>
<%= l @unit.date_end, format: :long %>
<%= @unit.author.name, author_path(unit.author_id) %>
<%= link_to 'Edit', edit_unit_path(@unit) %>
</div>