config/routes.rb
Rails.application.routes.draw do

  devise_for :users
#   devise_scope :user do get "/users/sign_in" => "devise/sessions#new"
# end
  # root 'devise/sessions#new'
  root 'units#index'

  get 'units/group/:id' => 'units#group', as: :units_group
  get 'units/search' => 'units#search', as: :units_search
  get 'units/complite/:id' => 'units#complite', as: :units_complite
  get 'units/group_complite/:id' => 'units#group_complite', as: :units_group_complite
  get 'authors/department/:id' => 'authors#department', as: :authors_department

  resources :authors, :users, :units, except: [:destroy]
  resources :temp_tasks, :departments, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TaskAgent" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <div class="input-group">
              <%= form_tag(units_search_path, method: :get, class: "navbar-form navbar-left") do %>
                <%= text_field_tag :term, params[:term], class: "form-control", placeholder: "Компания" %>
                <span class="input-group-btn">
                  <%= submit_tag 'Поиск', class: "btn btn-default find" %>
                </span>
              <% end %>

            <ul class="nav navbar-nav navbar-right text-size">
              <% if user_signed_in? %>
                <li><%= content_tag(:p, "Вы вошли как: " + current_user.name, class: ["navbar-text"]) %></li>
                <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
              <% else %>
                <li>
                  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %>
                </li>
                <li>
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %> 
                </li>
              <% end %>
                    

                <li>          
                  <a class="btn btn-lg navbar-link" id="home_btn">
                    <span class="glyphicon glyphicon-home"></span>
                  </a>    
                </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>

    <footer class="footer">
      &copy; Xihris 2017
    </footer>

  </body>
</html>